#!/bin/bash

if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  source "/usr/local/rvm/scripts/rvm"
fi

cd `pwd` && bundle exec ruby -rrubygems -e "require 'xcode-yamlizer'; XcodeYamlizer.run_pre_commit"
